// modules/lang.js
const translations = {
  es: {
    title: 'Creador de CV',
    formTitle: 'Rellena tus datos',
    previewTitle: 'Vista previa del CV',
    fullName: 'Nombre completo',
    email: 'Correo electrónico',
    phone: 'Teléfono',
    linkedIn: 'Perfil de LinkedIn',
    github: 'Perfil de GitHub',
    skills: 'Habilidades',
    education: 'Educación',
    experience: 'Experiencia',
    generateBtn: 'Generar vista previa',
    clearBtn: 'Limpiar',
    exportBtn: 'Exportar como .txt',
    alertNoPreview: 'Primero debes generar la vista previa antes de exportar.',
  },
  en: {
    title: 'Resume Builder',
    formTitle: 'Fill in your details',
    previewTitle: 'Resume Preview',
    fullName: 'Full Name',
    email: 'Email',
    phone: 'Phone',
    linkedIn: 'LinkedIn Profile',
    github: 'GitHub Profile',
    skills: 'Skills',
    education: 'Education',
    experience: 'Experience',
    generateBtn: 'Generate Preview',
    clearBtn: 'Clear',
    exportBtn: 'Export as .txt',
    alertNoPreview: 'You must generate the preview before exporting.',
  },
  gl: {
    title: 'Construtor de CV',
    formTitle: 'Enche os teus datos',
    previewTitle: 'Vista previa do CV',
    fullName: 'Nome completo',
    email: 'Correo electrónico',
    phone: 'Teléfono',
    linkedIn: 'Perfil de LinkedIn',
    github: 'Perfil de GitHub',
    skills: 'Habilidades',
    education: 'Formación',
    experience: 'Experiencia',
    generateBtn: 'Xerar vista previa',
    clearBtn: 'Limpar',
    exportBtn: 'Exportar como .txt',
    alertNoPreview: 'Primeiro debes xerar a vista previa antes de exportar.',
  }
};

export default translations;
